name: immich
services:
  immich-server:
    container_name: immich_server
    image: example.com/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    volumes:
    - ${UPLOAD_LOCATION}:/usr/src/app/upload
    - /etc/localtime:/etc/localtime:ro
    env_file:
    - .env
    restart: always
    healthcheck:
      disable: false
    labels:
    - traefik.enable=true
    - traefik.docker.network=traefik
    - traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)
    - traefik.http.routers.immich.entrypoints=websecure
    - traefik.http.routers.immich.tls.certresolver=letsencrypt
    - traefik.http.routers.immich.middlewares=chain-immich@file
    - traefik.http.services.immich.loadbalancer.server.port=2283
    - homepage.group=Media
    - homepage.name=Immich Server
    - homepage.icon=immich
    - homepage.href=https://example.com
    networks:
    - default
    - traefik
  immich-machine-learning:
    container_name: immich_machine_learning
    image: example.com/immich-app/immich-machine-learning:${IMMICH_VERSION:-release-openvino}
    extends:
      file: hwaccel.ml.yml
      service: openvino
    volumes:
        - model-cache:/cache
        - /dev/dri:/dev/dri
    
    env_file:
    - .env
    restart: always
    healthcheck:
      disable: false
  immich-redis:
    container_name: immich_redis
    image: example.com/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    labels:
    - homepage.exclude=true
  database:
    container_name: immich_postgres
    image: example.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    volumes:
    - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}"
        --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures),
        0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user",
      public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    env_file:
    - .env
    labels:
    - homepage.exclude=true
volumes:
  model-cache: null
networks:
  default:
    driver: bridge
  traefik:
    external: true
