
services:
  broker:
    image: example.com/library/redis:8
    container_name: paperless-redis
    restart: unless-stopped
    volumes:
    - /docker/appdata/paperless-ngx/redisdata:/data
  db:
    image: example.com/library/postgres:18
    container_name: paperless-db
    restart: unless-stopped
    volumes:
    - /docker/appdata/paperless-ngx/db:/var/lib/postgresql
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: ${PAPERLESS_POSTGRES_PASSWORD}
  gotenberg:
    image: example.com/gotenberg/gotenberg:8.25
    container_name: paperless-gotenberg
    restart: unless-stopped
    command:
    - gotenberg
    - --chromium-disable-javascript=true
    - --chromium-allow-list=file:///tmp/.*
  tika:
    image: example.com/apache/tika:latest
    container_name: paperless-tika
    restart: unless-stopped
  paperless:
    image: example.com/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
    - db
    - broker
    - gotenberg
    - tika
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      USERMAP_UID: ${PUID}
      USERMAP_GID: ${PGID}
      PAPERLESS_TIME_ZONE: ${TZ}
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBPORT: '5432'
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: ${PAPERLESS_POSTGRES_PASSWORD}
      PAPERLESS_TIKA_ENABLED: '1'
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_URL: https://example.com
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TASK_WORKERS: '4'
      PAPERLESS_THREADS_PER_WORKER: '2'
    volumes:
    - /docker/appdata/paperless-ngx/data:/usr/src/paperless/data
    - /mnt/storagebox/paperless/media:/usr/src/paperless/media
    - /mnt/storagebox/paperless/export:/usr/src/paperless/export
    - /mnt/storagebox/paperless/consume:/usr/src/paperless/consume
    labels:
    - traefik.enable=true
    - traefik.docker.network=traefik
    - traefik.http.routers.paperless.rule=Host(`paperless.${DOMAIN}`)
    - traefik.http.routers.paperless.entrypoints=websecure
    - traefik.http.routers.paperless.tls.certresolver=letsencrypt
    - traefik.http.services.paperless.loadbalancer.server.port=8000
    networks:
    - default
    - traefik
networks:
  default:
    
    internal: true
  traefik:
    external: true
